-- =============================================================================
-- 1. PUNTOS DE INTERÉS (POIs) - 50 REGISTROS
-- =============================================================================
INSERT INTO pois (nombre, descripcion, categoria, ciudad, latitud, longitud, image_url) VALUES
                                                                                            ('La Giralda', 'Torre campanario de la Catedral de Sevilla.', 'Monumento', 'Sevilla', 37.3862, -5.9925, 'https://bit.ly/giralda'),
                                                                                            ('Real Alcazar', 'Palacio real de origen mudejar.', 'Monumento', 'Sevilla', 37.3831, -5.9902, 'https://bit.ly/alcazar'),
                                                                                            ('Plaza de Espana', 'Conjunto arquitectonico unico de 1929.', 'Plaza', 'Sevilla', 37.3772, -5.9869, 'https://bit.ly/espana'),
                                                                                            ('Torre del Oro', 'Torre defensiva del siglo XIII.', 'Monumento', 'Sevilla', 37.3824, -5.9964, 'https://bit.ly/oro'),
                                                                                            ('Las Setas', 'Estructura moderna con vistas panorámicas.', 'Moderno', 'Sevilla', 37.3942, -5.9917, 'https://bit.ly/setas'),
                                                                                            ('Parque Maria Luisa', 'Principal pulmon verde de la ciudad.', 'Parque', 'Sevilla', 37.3755, -5.9890, 'https://bit.ly/parque'),
                                                                                            ('Archivo de Indias', 'Documentacion historica de las colonias.', 'Museo', 'Sevilla', 37.3845, -5.9930, 'https://bit.ly/indias'),
                                                                                            ('Barrio Santa Cruz', 'Antigua juderia llena de encanto.', 'Barrio', 'Sevilla', 37.3851, -5.9905, 'https://bit.ly/barrio'),
                                                                                            ('Palacio de las Duenas', 'Residencia historica de la Casa de Alba.', 'Palacio', 'Sevilla', 37.3944, -5.9892, 'https://bit.ly/duenas'),
                                                                                            ('Plaza de Toros Maestranza', 'Coso taurino historico.', 'Cultura', 'Sevilla', 37.3861, -5.9982, 'https://bit.ly/toros'),
                                                                                            ('Museo de Bellas Artes', 'Segunda pinacoteca mas importante de España.', 'Museo', 'Sevilla', 37.3925, -5.9996, 'https://bit.ly/artes-sev'),
                                                                                            ('Iglesia del Salvador', 'Gran templo barroco sevillano.', 'Monumento', 'Sevilla', 37.3902, -5.9936, 'https://bit.ly/salvador'),
                                                                                            ('Teatro de la Maestranza', 'Espacio cultural frente al río.', 'Teatro', 'Sevilla', 37.3841, -5.9985, 'https://bit.ly/teatro-m'),
                                                                                            ('Puente de Triana', 'Puente de hierro sobre el Guadalquivir.', 'Puente', 'Sevilla', 37.3858, -6.0006, 'https://bit.ly/triana-p'),
                                                                                            ('Casa de Pilatos', 'Palacio renacentista andaluz.', 'Palacio', 'Sevilla', 37.3899, -5.9871, 'https://bit.ly/pilatos'),
                                                                                            ('Alcazaba Malaga', 'Fortaleza musulmana palaciega.', 'Monumento', 'Málaga', 36.7212, -4.4158, 'https://bit.ly/malaga-alc'),
                                                                                            ('Teatro Romano', 'Restos de la Hispania Romana.', 'Monumento', 'Málaga', 36.7210, -4.4172, 'https://bit.ly/teatro'),
                                                                                            ('Castillo Gibralfaro', 'Fortificacion con las mejores vistas.', 'Monumento', 'Málaga', 36.7225, -4.4111, 'https://bit.ly/gibral'),
                                                                                            ('Catedral de Malaga', 'Conocida como La Manquita.', 'Monumento', 'Málaga', 36.7202, -4.4193, 'https://bit.ly/cat-mal'),
                                                                                            ('Museo Picasso', 'Obras originales del genio malagueno.', 'Museo', 'Málaga', 36.7216, -4.4184, 'https://bit.ly/picasso'),
                                                                                            ('Muelle Uno', 'Zona comercial y de ocio del puerto.', 'Ocio', 'Málaga', 36.7175, -4.4140, 'https://bit.ly/muelle'),
                                                                                            ('Playa Malagueta', 'Playa urbana mas emblemática.', 'Playa', 'Málaga', 36.7190, -4.4050, 'https://bit.ly/malagueta'),
                                                                                            ('Museo Pompidou', 'Centro de arte contemporáneo.', 'Museo', 'Málaga', 36.7185, -4.4125, 'https://bit.ly/pompidou'),
                                                                                            ('Mercado Atarazanas', 'Mercado historico con vidrieras.', 'Mercado', 'Málaga', 36.7188, -4.4239, 'https://bit.ly/atarazanas'),
                                                                                            ('Calle Larios', 'Calle comercial principal de Malaga.', 'Comercio', 'Málaga', 36.7195, -4.4210, 'https://bit.ly/larios'),
                                                                                            ('La Alhambra', 'Ciudad palatina nazarí.', 'Monumento', 'Granada', 37.1760, -3.5881, 'https://bit.ly/alhambra'),
                                                                                            ('Generalife', 'Jardines y palacio de descanso real.', 'Monumento', 'Granada', 37.1768, -3.5849, 'https://bit.ly/gen-life'),
                                                                                            ('Mirador San Nicolas', 'Mejor vista de la Alhambra al atardecer.', 'Mirador', 'Granada', 37.1811, -3.5926, 'https://bit.ly/snicolas'),
                                                                                            ('Catedral Granada', 'Catedral renacentista de gran tamaño.', 'Monumento', 'Granada', 37.1765, -3.5991, 'https://bit.ly/cat-gra'),
                                                                                            ('Sacromonte', 'Barrio de cuevas y zambras flamencas.', 'Barrio', 'Granada', 37.1824, -3.5855, 'https://bit.ly/sacro'),
                                                                                            ('Carrera del Darro', 'Calle empedrada junto al río.', 'Calle', 'Granada', 37.1785, -3.5910, 'https://bit.ly/darro'),
                                                                                            ('Monasterio de la Cartuja', 'Joyon del barroco español.', 'Monumento', 'Granada', 37.1920, -3.6000, 'https://bit.ly/cartuja'),
                                                                                            ('Parque de las Ciencias', 'Museo interactivo de ciencia.', 'Museo', 'Granada', 37.1625, -3.6060, 'https://bit.ly/ciencias-gr'),
                                                                                            ('Banos Arabes El Banuelo', 'Banos del siglo XI.', 'Monumento', 'Granada', 37.1788, -3.5915, 'https://bit.ly/banuelo'),
                                                                                            ('Corral del Carbon', 'Antigua alhóndiga andalusí.', 'Monumento', 'Granada', 37.1755, -3.5985, 'https://bit.ly/carbon'),
                                                                                            ('Catedral de Cadiz', 'Catedral frente al oceano Atlántico.', 'Monumento', 'Cádiz', 36.5289, -6.2952, 'https://bit.ly/cat-cad'),
                                                                                            ('Playa de la Caleta', 'Playa situada en el casco histórico.', 'Playa', 'Cádiz', 36.5298, -6.3055, 'https://bit.ly/caleta'),
                                                                                            ('Torre Tavira', 'Vigía oficial con cámara oscura.', 'Mirador', 'Cádiz', 36.5317, -6.2974, 'https://bit.ly/tavira'),
                                                                                            ('Castillo Sta Catalina', 'Fortaleza militar frente al mar.', 'Monumento', 'Cádiz', 36.5333, -6.3058, 'https://bit.ly/catalina'),
                                                                                            ('Castillo de San Sebastian', 'Fortaleza en un islote.', 'Monumento', 'Cádiz', 36.5288, -6.3115, 'https://bit.ly/sebastian'),
                                                                                            ('Parque Genoves', 'Jardín botánico con especies exoticas.', 'Parque', 'Cádiz', 36.5362, -6.3045, 'https://bit.ly/genoves'),
                                                                                            ('Gran Teatro Falla', 'Cuna del Carnaval gaditano.', 'Teatro', 'Cádiz', 36.5328, -6.3025, 'https://bit.ly/falla'),
                                                                                            ('Plaza de las Flores', 'Plaza pintoresca con puestos de flores.', 'Plaza', 'Cádiz', 36.5311, -6.2979, 'https://bit.ly/flores-cad'),
                                                                                            ('Puente de la Pepa', 'Impresionante obra de ingenieria moderna.', 'Puente', 'Cádiz', 36.5235, -6.2550, 'https://bit.ly/pepa'),
                                                                                            ('Ayuntamiento de Cadiz', 'Edificio neoclasico central.', 'Monumento', 'Cádiz', 36.5295, -6.2925, 'https://bit.ly/ayto-cad'),
                                                                                            ('Yacimiento Gadir', 'Restos de la ciudad fenicia.', 'Museo', 'Cádiz', 36.5318, -6.2985, 'https://bit.ly/gadir'),
                                                                                            ('Plaza de Mina', 'Plaza con museos y mucha vegetación.', 'Plaza', 'Cádiz', 36.5342, -6.2965, 'https://bit.ly/mina'),
                                                                                            ('Mercado Central Cadiz', 'Gastronomia local y pescado fresco.', 'Mercado', 'Cádiz', 36.5312, -6.2995, 'https://bit.ly/mercado-cad'),
                                                                                            ('Oratorio San Felipe Neri', 'Lugar de la primera constitucion.', 'Monumento', 'Cádiz', 36.5331, -6.2999, 'https://bit.ly/neri'),
                                                                                            ('Baluarte de la Candelaria', 'Espacio defensivo reconvertido en cultural.', 'Monumento', 'Cádiz', 36.5368, -6.2990, 'https://bit.ly/candelaria');

-- =============================================================================
-- 2. HOTELES - 50 REGISTROS
-- =============================================================================
INSERT INTO hoteles (nombre, estrellas, precio_noche, direccion, tiene_piscina, ciudad, latitud, longitud) VALUES
                                                                                                               ('Hotel Alfonso XIII', 5, 450.0, 'San Fernando 2', true, 'Sevilla', 37.3830, -5.9920),
                                                                                                               ('Hotel Colon Gran Melia', 5, 300.0, 'Canalejas 1', true, 'Sevilla', 37.3890, -5.9980),
                                                                                                               ('Las Casas de la Juderia', 4, 180.0, 'Santa Maria 5', true, 'Sevilla', 37.3851, -5.9905),
                                                                                                               ('Hotel Giralda Center', 4, 140.0, 'Juan de Mata', true, 'Sevilla', 37.3812, -5.9855),
                                                                                                               ('Hotel NH Plaza Armas', 4, 110.0, 'Marques de Paradas', true, 'Sevilla', 37.3910, -6.0020),
                                                                                                               ('Hotel Vincci La Rabida', 4, 155.0, 'Castelar 24', false, 'Sevilla', 37.3868, -5.9960),
                                                                                                               ('Hotel Becquer', 4, 125.0, 'Reyes Catolicos 4', false, 'Sevilla', 37.3885, -6.0001),
                                                                                                               ('Hotel Inglaterra', 4, 165.0, 'Plaza Nueva 10', false, 'Sevilla', 37.3888, -5.9958),
                                                                                                               ('Mercer Sevilla', 5, 420.0, 'Castelar 26', true, 'Sevilla', 37.3870, -5.9962),
                                                                                                               ('Hotel Silken Al-Andalus', 4, 85.0, 'Avenida Holanda', true, 'Sevilla', 37.3565, -5.9865),
                                                                                                               ('Hotel Don Paco', 3, 95.0, 'Plaza Jeronimo de Cordoba', true, 'Sevilla', 37.3932, -5.9875),
                                                                                                               ('Hotel Amadeus', 4, 145.0, 'Farnesio 6', false, 'Sevilla', 37.3860, -5.9901),
                                                                                                               ('Hotel Macia Kubb', 4, 105.0, 'Plaza del Carmen', true, 'Sevilla', 37.3915, -5.9850),
                                                                                                               ('Hotel Zenit Sevilla', 4, 115.0, 'Pagés del Corro', false, 'Sevilla', 37.3825, -6.0025),
                                                                                                               ('Gran Hotel Miramar', 5, 380.0, 'Paseo Reding 22', true, 'Málaga', 36.7205, -4.4080),
                                                                                                               ('AC Malaga Palacio', 4, 160.0, 'Cortina del Muelle 1', true, 'Málaga', 36.7201, -4.4200),
                                                                                                               ('Hotel Molina Lario', 4, 175.0, 'Molina Lario 20', true, 'Málaga', 36.7195, -4.4198),
                                                                                                               ('Hotel Vincci Posada del Patio', 5, 210.0, 'Pasillo Santa Isabel', true, 'Málaga', 36.7215, -4.4255),
                                                                                                               ('Hotel NH Malaga', 4, 130.0, 'Avenida Andalucia', false, 'Málaga', 36.7185, -4.4285),
                                                                                                               ('Hotel Room Mate Larios', 4, 150.0, 'Marqués de Larios 2', false, 'Málaga', 36.7198, -4.4212),
                                                                                                               ('Hotel Barcelo Malaga', 4, 140.0, 'Heroe de Sostoa', false, 'Málaga', 36.7130, -4.4325),
                                                                                                               ('Hotel MS Maestranza', 4, 120.0, 'Maestranza 15', false, 'Málaga', 36.7198, -4.4135),
                                                                                                               ('Hotel Ilunion Malaga', 4, 110.0, 'Paseo Maritimo', true, 'Málaga', 36.7115, -4.4280),
                                                                                                               ('Hotel Soho Boutique Castillo', 4, 165.0, 'Paseo de Reding', true, 'Málaga', 36.7210, -4.4095),
                                                                                                               ('Hotel Don Curro', 3, 90.0, 'Sancha de Lara', false, 'Málaga', 36.7192, -4.4218),
                                                                                                               ('Alhambra Palace', 5, 260.0, 'Peña Partida 2', false, 'Granada', 37.1740, -3.5890),
                                                                                                               ('Hotel Eurostars Washington Irving', 5, 220.0, 'Paseo del Generalife', true, 'Granada', 37.1745, -3.5865),
                                                                                                               ('Hotel NH Collection Victoria', 4, 140.0, 'Puerta Real de España', false, 'Granada', 37.1745, -3.6000),
                                                                                                               ('Hotel Barcelo Carmen Granada', 4, 115.0, 'Acera del Darro', true, 'Granada', 37.1718, -3.6005),
                                                                                                               ('Hotel Melia Granada', 4, 125.0, 'Ángel Ganivet 7', false, 'Granada', 37.1732, -3.5995),
                                                                                                               ('Hotel Saray', 4, 95.0, 'Paseo del Violon', true, 'Granada', 37.1665, -3.5985),
                                                                                                               ('Hotel Macia Condor', 4, 85.0, 'Avenida de la Constitución', false, 'Granada', 37.1835, -3.6035),
                                                                                                               ('Hotel Palacio de Santa Paula', 5, 280.0, 'Gran Via de Colon', false, 'Granada', 37.1785, -3.5998),
                                                                                                               ('Hotel Vincci Albayzin', 4, 110.0, 'Avenida de la Constitución', false, 'Granada', 37.1715, -3.6015),
                                                                                                               ('Hotel Parador de Granada', 4, 320.0, 'Real de la Alhambra', false, 'Granada', 37.1762, -3.5855),
                                                                                                               ('Hotel Marquis Issa', 4, 105.0, 'Plaza de los Girones', false, 'Granada', 37.1752, -3.5955),
                                                                                                               ('Parador de Cadiz', 4, 185.0, 'Duque de Najera 9', true, 'Cádiz', 36.5330, -6.3040),
                                                                                                               ('Hotel Playa Victoria', 4, 135.0, 'Glorieta Ingeniero', true, 'Cádiz', 36.5050, -6.2750),
                                                                                                               ('Hotel Senator Cadiz', 4, 110.0, 'Rubio y Diaz 1', true, 'Cádiz', 36.5320, -6.2940),
                                                                                                               ('Hotel Occidental Cadiz', 4, 100.0, 'Avenida de Andalucia', false, 'Cádiz', 36.5125, -6.2815),
                                                                                                               ('Hotel Monte de la Caleta', 3, 95.0, 'Avenida Duque de Najera', false, 'Cádiz', 36.5315, -6.3045),
                                                                                                               ('Hotel Convento Cadiz', 3, 85.0, 'Santo Domingo 2', false, 'Cádiz', 36.5292, -6.2905),
                                                                                                               ('Hotel Tryp La Caleta', 4, 115.0, 'Avenida Amilcar Barca', false, 'Cádiz', 36.5090, -6.2790),
                                                                                                               ('Hotel Regio Cadiz', 3, 75.0, 'Avenida Ana de Viya', false, 'Cádiz', 36.5075, -6.2775),
                                                                                                               ('Hotel Boutique Casa de las Cuatro Torres', 4, 155.0, 'Plaza de España', false, 'Cádiz', 36.5348, -6.2915),
                                                                                                               ('Hotel Plaza de la Luz', 3, 90.0, 'Calle de la Palma', false, 'Cádiz', 36.5305, -6.3050),
                                                                                                               ('Hotel Argantonio', 3, 105.0, 'Calle Argantonio', false, 'Cádiz', 36.5325, -6.2955),
                                                                                                               ('Hotel Las Cortes de Cadiz', 3, 95.0, 'Calle San Francisco', false, 'Cádiz', 36.5335, -6.2935),
                                                                                                               ('Hotel Patagonia Sur', 3, 80.0, 'Calle Cobos', false, 'Cádiz', 36.5298, -6.2945),
                                                                                                               ('Hotel Spa Puerta Tierra', 4, 105.0, 'Avenida de Andalucia', true, 'Cádiz', 36.5235, -6.2875);

-- =============================================================================
-- 3. RESTAURANTES - 50 REGISTROS
-- =============================================================================
INSERT INTO restaurant (name, city, cuisine_type, rating, address, average_price, latitud, longitud) VALUES
                                                                                                         ('El Rinconcillo', 'Sevilla', 'Tradicional', 4.7, 'Gerona 40', 25.0, 37.3923, -5.9890),
                                                                                                         ('Abades Triana', 'Sevilla', 'Fusion', 4.5, 'Betis 69', 65.0, 37.3820, -6.0010),
                                                                                                         ('Bodega Santa Cruz', 'Sevilla', 'Tapas', 4.6, 'Rodrigo Caro 1', 18.0, 37.3858, -5.9918),
                                                                                                         ('Eslava', 'Sevilla', 'Gourmet Tapas', 4.8, 'Eslava 3', 35.0, 37.3970, -5.9950),
                                                                                                         ('Canabota', 'Sevilla', 'Pescados', 4.9, 'Orfila 3', 85.0, 37.3930, -5.9935),
                                                                                                         ('Casa Robles', 'Sevilla', 'Andaluza', 4.5, 'Alvarez Quintero 58', 45.0, 37.3860, -5.9930),
                                                                                                         ('La Azotea', 'Sevilla', 'Creativa', 4.6, 'Jesus del Gran Poder', 40.0, 37.3955, -5.9945),
                                                                                                         ('Restaurante Oriza', 'Sevilla', 'Vasca-Andaluza', 4.4, 'San Fernando 41', 70.0, 37.3828, -5.9915),
                                                                                                         ('Casa Ricardo', 'Sevilla', 'Tapas Clasicas', 4.7, 'Hernan Cortes 2', 20.0, 37.3958, -5.9965),
                                                                                                         ('Perro Viejo', 'Sevilla', 'Moderna', 4.3, 'Arguijo 3', 30.0, 37.3928, -5.9932),
                                                                                                         ('Bar Alfalfa', 'Sevilla', 'Tapas de mercado', 4.4, 'Calle Alfalfa', 22.0, 37.3905, -5.9910),
                                                                                                         ('El Tragaluz', 'Sevilla', 'Italiana-Andaluza', 4.2, 'Calle Real Carreteria', 28.0, 37.3855, -5.9975),
                                                                                                         ('La Brunilda', 'Sevilla', 'Tapas de autor', 4.7, 'Galera 5', 25.0, 37.3852, -5.9995),
                                                                                                         ('Mechela Restaurante', 'Sevilla', 'Creativa', 4.6, 'Calle Bailen', 50.0, 37.3908, -5.9998),
                                                                                                         ('Restaurante Jaylu', 'Sevilla', 'Marisco', 4.8, 'Lopez de Gomara', 90.0, 37.3825, -6.0095),
                                                                                                         ('El Pimpi', 'Málaga', 'Vinos y Bodega', 4.6, 'Calle Granada 62', 25.0, 36.7218, -4.4170),
                                                                                                         ('Los Mellizos', 'Málaga', 'Mariscos', 4.5, 'Sancha de Lara 7', 50.0, 36.7192, -4.4215),
                                                                                                         ('Restaurante Jose Carlos Garcia', 'Málaga', 'Alta Cocina', 4.9, 'Puerto de Malaga', 130.0, 36.7170, -4.4145),
                                                                                                         ('El Tintero', 'Málaga', 'Pescaito frito', 4.1, 'Playa del Dedo', 22.0, 36.7185, -4.3450),
                                                                                                         ('Refectorium', 'Málaga', 'Tradicional', 4.6, 'Calle Postigo de los Abades', 45.0, 36.7202, -4.4190),
                                                                                                         ('Restaurante Kaleja', 'Málaga', 'Gourmet', 4.8, 'Calle Marques de Guadiaro', 95.0, 36.7225, -4.4185),
                                                                                                         ('Cortijo de Pepe', 'Málaga', 'Asador', 4.4, 'Plaza de la Merced', 30.0, 36.7235, -4.4175),
                                                                                                         ('La Cosmopolita', 'Málaga', 'Guisos y Tapas', 4.7, 'Calle Jose Denis Belgrano', 40.0, 36.7210, -4.4195),
                                                                                                         ('Chiringuito El Cabra', 'Málaga', 'Pescado Playa', 4.2, 'Paseo Maritimo El Palo', 28.0, 36.7175, -4.3485),
                                                                                                         ('Meson Mariano', 'Málaga', 'Tradicional Malagueno', 4.5, 'Calle Casapalma', 35.0, 36.7228, -4.4198),
                                                                                                         ('Uvedoble Taberna', 'Málaga', 'Moderna', 4.6, 'Calle Cister', 32.0, 36.7212, -4.4182),
                                                                                                         ('Marisqueria Godoy', 'Málaga', 'Mariscos Puerto', 4.3, 'Muelle Uno', 55.0, 36.7168, -4.4138),
                                                                                                         ('El Faro de Cadiz', 'Cádiz', 'Alta Cocina Marina', 4.8, 'San Felix 15', 65.0, 36.5290, -6.3010),
                                                                                                         ('Ventorrillo El Chato', 'Cádiz', 'Historica', 4.7, 'Via Augusta', 55.0, 36.4850, -6.2650),
                                                                                                         ('Restaurante Elcano', 'Cádiz', 'Vistas al mar', 4.4, 'Paseo Maritimo', 40.0, 36.5025, -6.2725),
                                                                                                         ('Balandro', 'Cádiz', 'Tapas y Restaurante', 4.6, 'Alameda Apodaca', 35.0, 36.5365, -6.2975),
                                                                                                         ('La Curiosidad de Mauro', 'Cádiz', 'Vanguardia', 4.7, 'Calle Veedor', 50.0, 36.5345, -6.2995),
                                                                                                         ('Taberna La Sorpresa', 'Cádiz', 'Vinos y Atun', 4.8, 'Calle Arbolí', 28.0, 36.5315, -6.2982),
                                                                                                         ('Casa Manteca', 'Cádiz', 'Taberna Tipica', 4.7, 'Calle Corralon de los Carros', 20.0, 36.5302, -6.3035),
                                                                                                         ('Restaurante Salicornia', 'Cádiz', 'Creativa', 4.5, 'Calle Plocia', 38.0, 36.5285, -6.2915),
                                                                                                         ('La Isleta de la Vina', 'Cádiz', 'Bohemio', 4.4, 'Calle Corralon', 22.0, 36.5308, -6.3042),
                                                                                                         ('Marisqueria Baro', 'Cádiz', 'Pescado Fresco', 4.3, 'Avenida Ana de Viya', 40.0, 36.5085, -6.2785),
                                                                                                         ('Aplomo', 'Cádiz', 'Culinaria Moderna', 4.6, 'Calle Plocia', 45.0, 36.5288, -6.2912),
                                                                                                         ('Los Manueles', 'Granada', 'Andaluza historica', 4.5, 'Reyes Catolicos 61', 25.0, 37.1765, -3.5970),
                                                                                                         ('Restaurante Chikito', 'Granada', 'Tradicional', 4.6, 'Plaza del Campillo', 45.0, 37.1725, -3.6005),
                                                                                                         ('Las Tomasas', 'Granada', 'Vistas Alhambra', 4.7, 'Carril de San Agustin', 60.0, 37.1808, -3.5915),
                                                                                                         ('El Claustro', 'Granada', 'Gourmet', 4.8, 'Gran Via de Colon', 75.0, 37.1788, -3.5995),
                                                                                                         ('Bodegas Castaneda', 'Granada', 'Tapas Clasicas', 4.6, 'Calle Almireceros', 20.0, 37.1768, -3.5975),
                                                                                                         ('La Fabula', 'Granada', 'Alta Cocina', 4.9, 'San Anton 28', 90.0, 37.1705, -3.6010),
                                                                                                         ('Taberna La Tana', 'Granada', 'Vinos y Quesos', 4.8, 'Placeta del Agua', 30.0, 37.1735, -3.5982),
                                                                                                         ('Oliver Restaurante', 'Granada', 'Tradicional', 4.4, 'Plaza de Pescaderia', 35.0, 37.1758, -3.5995),
                                                                                                         ('Alcayata Tapas', 'Granada', 'Moderna', 4.5, 'Calle de la Palma', 25.0, 37.1742, -3.5935),
                                                                                                         ('Restaurante Carmen de Aben Humeya', 'Granada', 'Vistas Alhambra', 4.7, 'Calle Convalecientes', 65.0, 37.1815, -3.5920),
                                                                                                         ('El Trillo', 'Granada', 'Cocina de Jardin', 4.6, 'Callejon de las Tomasas', 50.0, 37.1810, -3.5912),
                                                                                                         ('Bar Diamantes', 'Granada', 'Pescaito Frito Tapas', 4.5, 'Calle Navas', 18.0, 37.1738, -3.5985);
-- =============================================================================
-- 4. ACTIVIDADES - 20 REGISTROS (5 POR CIUDAD)
-- =============================================================================

-- SEVILLA
INSERT INTO activity (nombre, descripcion, precio, duracion, ciudad, latitud, longitud, exterior) VALUES
                                                                                                      ('Tour de Misterios', 'Recorrido nocturno por leyendas de Sevilla.', 15.0, '2h', 'Sevilla', 37.3858, -5.9918, true),
                                                                                                      ('Paseo en Coche de Caballos', 'Tour clasico por el Parque Maria Luisa.', 45.0, '45min', 'Sevilla', 37.3770, -5.9870, true),
                                                                                                      ('Espectaculo Flamenco', 'Show en directo en el barrio de Triana.', 25.0, '1.5h', 'Sevilla', 37.3850, -6.0010, false),
                                                                                                      ('Crucero por el Guadalquivir', 'Vistas de la ciudad desde el rio.', 18.0, '1h', 'Sevilla', 37.3824, -5.9964, true),
                                                                                                      ('Taller de Tapas', 'Aprende a cocinar platos tipicos.', 50.0, '3h', 'Sevilla', 37.3940, -5.9920, false);

-- MALAGA
INSERT INTO activity (nombre, descripcion, precio, duracion, ciudad, latitud, longitud, exterior) VALUES
                                                                                                      ('Tour de Picasso', 'Ruta por los lugares de infancia del pintor.', 12.0, '2h', 'Málaga', 36.7216, -4.4184, true),
                                                                                                      ('Alquiler de Kayak', 'Remo suave por la costa de la Malagueta.', 20.0, '1h', 'Málaga', 36.7190, -4.4050, true),
                                                                                                      ('Cata de Vinos Dulces', 'Degustacion en bodega historica.', 30.0, '1.5h', 'Málaga', 36.7218, -4.4170, false),
                                                                                                      ('Visita Nocturna Alcazaba', 'Recorrido bajo las estrellas.', 10.0, '1h', 'Málaga', 36.7212, -4.4158, true),
                                                                                                      ('Entrada Museo Ruso', 'Arte de las vanguardias rusas.', 9.0, '2h', 'Málaga', 36.7030, -4.4400, false);

-- GRANADA
INSERT INTO activity (nombre, descripcion, precio, duracion, ciudad, latitud, longitud, exterior) VALUES
                                                                                                      ('Tour Albaicin y Sacromonte', 'Paseo por los barrios mas tipicos.', 15.0, '2.5h', 'Granada', 37.1811, -3.5926, true),
                                                                                                      ('Banos Arabes Hammam', 'Relajacion en aguas termales.', 40.0, '1.5h', 'Granada', 37.1788, -3.5915, false),
                                                                                                      ('Taller de Ceramica Taracea', 'Artesania tradicional nazari.', 35.0, '2h', 'Granada', 37.1760, -3.5980, false),
                                                                                                      ('Senderismo Alhambra', 'Ruta por los bosques de la colina.', 0.0, '3h', 'Granada', 37.1740, -3.5850, true),
                                                                                                      ('Noche de Cuevas', 'Zambra flamenca original.', 25.0, '1.5h', 'Granada', 37.1824, -3.5855, false);

-- CADIZ
INSERT INTO activity (nombre, descripcion, precio, duracion, ciudad, latitud, longitud, exterior) VALUES
                                                                                                      ('Tour de la Constitucion', 'Ruta por los hitos de La Pepa.', 10.0, '2h', 'Cádiz', 36.5295, -6.2925, true),
                                                                                                      ('Avistamiento de Cetaceos', 'Salida en barco por la bahia.', 45.0, '3h', 'Cádiz', 36.5350, -6.2850, true),
                                                                                                      ('Entrada Camara Oscura', 'Vistas en tiempo real de la ciudad.', 7.0, '45min', 'Cádiz', 36.5317, -6.2974, false),
                                                                                                      ('Ruta Gastronomica', 'Cata de pescaos y vinos de Jerez.', 35.0, '2h', 'Cádiz', 36.5312, -6.2995, false),
                                                                                                      ('Surf en la Victoria', 'Clase de iniciacion en la playa.', 25.0, '1.5h', 'Cádiz', 36.5050, -6.2750, true);